const express = require('express');
const { authMiddleware } = require('../middleware/authMiddleware');
const { getNearbyUsers } = require('../controllers/getNearbyUsers');
const upload = require('../middleware/upload');
const { getIndividualUser, searchUsersByUsernameOrLocation, uploadProfileImage,uploadPostImage,  getUserImage, updateFullName, deleteProfileImage, deleteProfile, getTopUsersByWorkoutTime, getUserFeed, uploadFeed, getMyFeed, deletePost, getFeedById, uploadReel, getUserReels} = require('../controllers/getIndividualUser');
const { reactToPost } = require('../controllers/PostReaction');
const { createComment, deleteComment, getCommentsByPost } = require('../controllers/createComment');
const uploadVideo = require('../middleware/uploadVideo');
const router = express.Router();

router.get('/nearby-users', authMiddleware, searchUsersByUsernameOrLocation);
router.get('/get', authMiddleware, getIndividualUser);
router.get('/search/:username', authMiddleware, searchUsersByUsernameOrLocation);
router.post('/uploadProfileImage', authMiddleware, upload.single('profileImage'), uploadProfileImage);
router.post('/uploadImage', authMiddleware, upload.single('postImage'), uploadPostImage);
router.get('/getImage/:userId', authMiddleware, getUserImage);
router.put('/update-fullname', authMiddleware, updateFullName);
router.put('/delete-profileimage', authMiddleware, deleteProfileImage);
router.delete('/deleteaccount', authMiddleware, deleteProfile);
router.get('/leaderboard',  getTopUsersByWorkoutTime);
router.get('/feed',  authMiddleware,  getUserFeed);
router.get('/feed/:id', authMiddleware, getFeedById);
router.delete('/feed/:postId', authMiddleware, deletePost);
router.get('/my-feed', authMiddleware, getMyFeed);
router.post('/feed/upload',  authMiddleware, upload.single('image'),  uploadFeed);
router.post('/feed/react', authMiddleware,  reactToPost);
router.post('/feed/comment', authMiddleware,  createComment);
router.delete('/feed/comment/:commentId', authMiddleware,  deleteComment);
router.get('/feed/comment/:postId', authMiddleware,  getCommentsByPost);
router.post('/reel/upload',  authMiddleware, uploadVideo.single('video'),  uploadReel);
router.get('/reel',  authMiddleware,  getUserReels);

module.exports = router;
