name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      env:
        DB_FITZOO_DATABASE: your_database_name
        DB_FITZOO_USERNAME: your_database_user
        DB_FITZOO_PASSWORD: your_database_password
        DB_FITZOO_HOST: your_database_host
        DB_FITZOO_DIALECT: postgres
      run: npm test